### ISSUE TITLE
Embedded links not working

### ISSUE THREAD

**Issue by phucnh22** [LDSSA/ds-prep-course-2022#1]
In the **Windows 10/11** [setup guides](https://github.com/LDSSA/ds-prep-course-2022#11a-windows-1011-setup), some reference links are not working. The reason is that the contents are only available in the 2021 repo, not in the 2022 repo as in the URL

![image](https://user-images.githubusercontent.com/71492005/159355514-4f0bf863-a0a5-4202-8209-9b9c21d58f8a.png)

**Comment by carlacotas** [comment]
Hi @phucnh22 ,

I will close this issue, the links are already updated and working :)
